name: modFramework
version: '1.0-SNAPSHOT'
main: wefeke.modFramework.modFramework
api-version: '1.21'
commands:
  startchallenge:
    description: Öffnet das Challenge Menü
    usage: /startchallenge
  toggleHunger:
    description: Hunger an/aus
    usage: /toggleHunger